baseURL = "https://lucasmun.me"
languageCode = "en-us"
title = "Lucas Mun's Engineering Blog"
theme = "hugo-lamp"
[params]
	logo = "/img/avatar.jpg" 
	linkedin = "lucas-mun-693689150"
	email = "lucasmun@vt.edu"
	

             
